insert into public.truffle_guides (
  truffle_type,
  latin_name,
  title_it,
  title_en,
  short_description_it,
  short_description_en,
  description_it,
  description_en,
  aroma_it,
  aroma_en,
  price_min_eur,
  price_max_eur,
  rarity,
  symbiotic_plants_it,
  symbiotic_plants_en,
  soil_composition_it,
  soil_composition_en,
  soil_structure_it,
  soil_structure_en,
  soil_ph_it,
  soil_ph_en,
  soil_altitude_it,
  soil_altitude_en,
  soil_humidity_it,
  soil_humidity_en,
  harvest_start_month,
  harvest_end_month,
  is_published,
  sort_order
)
values
(
  'TUBER_MAGNATUM',
  'Tuber magnatum Pico',
  'Tartufo Bianco Pregiato',
  'Precious White Truffle',
  'Il piu raro e prezioso, dal profumo intenso e inconfondibile.',
  'The rarest and most prized, with an intense unmistakable aroma.',
  'Tartufo spontaneo molto pregiato, apprezzato per rarita, intensita aromatica e forte valore gastronomico.',
  'A highly prized wild truffle appreciated for its rarity, aromatic intensity, and outstanding culinary value.',
  'Intenso e complesso, con note di aglio, miele e formaggio stagionato.',
  'Intense and complex, with notes of garlic, honey, and aged cheese.',
  1000,
  5000,
  5,
  ARRAY['Quercia','Pioppo','Salice','Tiglio'],
  ARRAY['Oak','Poplar','Willow','Linden'],
  'Calcareo e ricco di minerali',
  'Calcareous and mineral-rich',
  'Soffice e ben drenato',
  'Soft and well-drained',
  'Subalcalino (7.5-8.0)',
  'Slightly alkaline (7.5-8.0)',
  '0-600 m',
  '0-600 m',
  'Moderata, con buona freschezza del suolo',
  'Moderate, with good soil freshness',
  9,
  12,
  true,
  1
),
(
  'TUBER_MELANOSPORUM',
  'Tuber melanosporum',
  'Tartufo Nero Pregiato',
  'Black Winter Truffle',
  'Elegante e persistente, e il nero piu ricercato dopo il bianco.',
  'Elegant and persistent, it is the most sought-after black truffle after the white.',
  'Tartufo nero di alta qualita, molto apprezzato in cucina per equilibrio aromatico e ampia versatilita.',
  'A high-quality black truffle prized in fine dining for its balanced aroma and versatility.',
  'Elegante e persistente, con note di cacao, sottobosco e terra umida.',
  'Elegant and persistent, with notes of cocoa, undergrowth, and moist earth.',
  300,
  1200,
  4,
  ARRAY['Quercia','Nocciolo'],
  ARRAY['Oak','Hazel'],
  'Calcareo',
  'Calcareous',
  'Compatto ma drenante',
  'Compact but well-draining',
  'Alcalino (7.5-8.5)',
  'Alkaline (7.5-8.5)',
  '200-1000 m',
  '200-1000 m',
  'Moderata',
  'Moderate',
  11,
  3,
  true,
  2
),
(
  'TUBER_AESTIVUM',
  'Tuber aestivum',
  'Tartufo Nero Estivo',
  'Summer Truffle',
  'Diffuso e versatile, ha un profumo piu delicato e un prezzo accessibile.',
  'Widely available and versatile, with a milder aroma and more accessible price.',
  'Tartufo estivo molto diffuso, apprezzato per la sua versatilita e per il profilo aromatico delicato.',
  'A common summer truffle appreciated for its versatility and gentle aromatic profile.',
  'Delicato, con note di nocciola e sottobosco leggero.',
  'Delicate, with notes of hazelnut and light undergrowth.',
  50,
  200,
  2,
  ARRAY['Quercia','Nocciolo','Carpino'],
  ARRAY['Oak','Hazel','Hornbeam'],
  'Calcareo o argilloso',
  'Calcareous or clayey',
  'Soffice',
  'Soft',
  'Neutro-alcalino',
  'Neutral to alkaline',
  '0-800 m',
  '0-800 m',
  'Media',
  'Moderate',
  5,
  8,
  true,
  3
),
(
  'TUBER_UNCINATUM',
  'Tuber uncinatum',
  'Tartufo Nero Uncinato',
  'Burgundy Truffle',
  'Piu intenso dell''estivo, con profilo aromatico autunnale.',
  'More intense than the summer truffle, with a richer autumn aroma.',
  'Variante autunnale piu profumata dell''aestivum, apprezzata per maggiore intensita e profondita aromatica.',
  'An autumn form with stronger aroma than aestivum, appreciated for its deeper flavor.',
  'Intenso, con note di nocciola, sottobosco e funghi secchi.',
  'Rich, with notes of hazelnut, forest floor, and dried mushrooms.',
  100,
  400,
  3,
  ARRAY['Quercia','Faggio'],
  ARRAY['Oak','Beech'],
  'Calcareo',
  'Calcareous',
  'Soffice e drenante',
  'Soft and well-drained',
  'Neutro-alcalino',
  'Neutral to alkaline',
  '200-900 m',
  '200-900 m',
  'Moderata',
  'Moderate',
  9,
  12,
  true,
  4
),
(
  'TUBER_BORCHII',
  'Tuber borchii',
  'Bianchetto',
  'Whitish Truffle',
  'Simile al bianco per famiglia aromatica, ma piu diretto e meno raffinato.',
  'Similar to white truffle in aroma family, but more direct and less refined.',
  'Tartufo chiaro di fine inverno e inizio primavera, apprezzato per il profumo deciso e il buon rapporto qualita-prezzo.',
  'A pale truffle harvested in late winter and early spring, valued for its bold aroma and accessible price.',
  'Forte, con note di aglio, terra e spezie leggere.',
  'Strong, with notes of garlic, earth, and light spice.',
  100,
  400,
  3,
  ARRAY['Pino','Quercia'],
  ARRAY['Pine','Oak'],
  'Sabbioso',
  'Sandy',
  'Sciolto',
  'Loose',
  'Leggermente alcalino',
  'Slightly alkaline',
  '0-500 m',
  '0-500 m',
  'Media',
  'Moderate',
  1,
  4,
  true,
  5
),
(
  'TUBER_BRUMALE',
  'Tuber brumale',
  'Tartufo Nero Invernale',
  'Winter Truffle',
  'Nero invernale dal profilo piu rustico e meno complesso del melanosporum.',
  'A winter black truffle with a more rustic and less complex profile than melanosporum.',
  'Tartufo nero invernale meno pregiato del melanosporum ma interessante per cucina e trasformazione.',
  'A winter black truffle less prized than melanosporum, but still valuable in cooking and processing.',
  'Terroso e deciso, meno complesso ma riconoscibile.',
  'Earthy and assertive, less complex but distinctive.',
  100,
  300,
  2,
  ARRAY['Quercia'],
  ARRAY['Oak'],
  'Calcareo',
  'Calcareous',
  'Compatto',
  'Compact',
  'Alcalino',
  'Alkaline',
  '200-800 m',
  '200-800 m',
  'Moderata',
  'Moderate',
  11,
  3,
  true,
  6
),
(
  'TUBER_MESENTERICUM',
  'Tuber mesentericum',
  'Tartufo Mesenterico',
  'Mesenteric Truffle',
  'Poco comune, si distingue per il profumo molto caratteristico.',
  'Less common and known for its very distinctive aroma.',
  'Tartufo nero poco diffuso, riconoscibile per il suo profilo aromatico intenso e divisivo.',
  'A less common black truffle recognizable for its intense and polarizing aromatic profile.',
  'Intenso e pungente, con note amare e sfumature catramose.',
  'Intense and pungent, with bitter and tar-like notes.',
  50,
  150,
  2,
  ARRAY['Faggio','Quercia'],
  ARRAY['Beech','Oak'],
  'Calcareo',
  'Calcareous',
  'Compatto',
  'Compact',
  'Alcalino',
  'Alkaline',
  '200-800 m',
  '200-800 m',
  'Media',
  'Moderate',
  9,
  1,
  true,
  7
),
(
  'TUBER_BRUMALE_MOSCHATUM',
  'Tuber brumale var. moschatum',
  'Tartufo Brumale Moscato',
  'Musky Brumal Truffle',
  'Variante del brumale dal profumo piu intenso e muschiato.',
  'A brumale variant with a stronger, musky aroma.',
  'Variante aromatica del brumale, interessante per intensita olfattiva e personalita marcata.',
  'An aromatic form of brumale valued for its stronger scent and marked character.',
  'Forte e muschiato, con tono animale e persistente.',
  'Strong and musky, with an animalic and persistent tone.',
  80,
  250,
  2,
  ARRAY['Quercia'],
  ARRAY['Oak'],
  'Calcareo',
  'Calcareous',
  'Compatto',
  'Compact',
  'Alcalino',
  'Alkaline',
  '200-800 m',
  '200-800 m',
  'Moderata',
  'Moderate',
  12,
  3,
  true,
  8
),
(
  'TUBER_MACROSPORUM',
  'Tuber macrosporum',
  'Tartufo Nero Liscio',
  'Smooth Black Truffle',
  'Raro e profumato, con scorza relativamente liscia e carattere deciso.',
  'Rare and aromatic, with a relatively smooth surface and strong character.',
  'Tartufo nero raro e apprezzato per il profumo intenso e la buona eleganza aromatica.',
  'A rare black truffle appreciated for its strong aroma and refined character.',
  'Intenso, con note di aglio, terra e sottobosco.',
  'Intense, with notes of garlic, earth, and undergrowth.',
  200,
  600,
  3,
  ARRAY['Quercia','Nocciolo'],
  ARRAY['Oak','Hazel'],
  'Calcareo',
  'Calcareous',
  'Soffice',
  'Soft',
  'Alcalino',
  'Alkaline',
  '100-700 m',
  '100-700 m',
  'Moderata',
  'Moderate',
  9,
  12,
  true,
  9
)
on conflict (truffle_type) do update
set
  latin_name = excluded.latin_name,
  title_it = excluded.title_it,
  title_en = excluded.title_en,
  short_description_it = excluded.short_description_it,
  short_description_en = excluded.short_description_en,
  description_it = excluded.description_it,
  description_en = excluded.description_en,
  aroma_it = excluded.aroma_it,
  aroma_en = excluded.aroma_en,
  price_min_eur = excluded.price_min_eur,
  price_max_eur = excluded.price_max_eur,
  rarity = excluded.rarity,
  symbiotic_plants_it = excluded.symbiotic_plants_it,
  symbiotic_plants_en = excluded.symbiotic_plants_en,
  soil_composition_it = excluded.soil_composition_it,
  soil_composition_en = excluded.soil_composition_en,
  soil_structure_it = excluded.soil_structure_it,
  soil_structure_en = excluded.soil_structure_en,
  soil_ph_it = excluded.soil_ph_it,
  soil_ph_en = excluded.soil_ph_en,
  soil_altitude_it = excluded.soil_altitude_it,
  soil_altitude_en = excluded.soil_altitude_en,
  soil_humidity_it = excluded.soil_humidity_it,
  soil_humidity_en = excluded.soil_humidity_en,
  harvest_start_month = excluded.harvest_start_month,
  harvest_end_month = excluded.harvest_end_month,
  is_published = excluded.is_published,
  sort_order = excluded.sort_order;
