// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN-9On0TfrsKbFc951Zze_gfUpYYnWvNY',
    appId: '1:227895447148:android:c0df2a3af3cdd342cad249',
    messagingSenderId: '227895447148',
    projectId: 'truffly-6368a',
    storageBucket: 'truffly-6368a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN3XV1in-jG2GU_nzdHElscXpY5iPv7hQ',
    appId: '1:227895447148:ios:166be1f9ce8ae64bcad249',
    messagingSenderId: '227895447148',
    projectId: 'truffly-6368a',
    storageBucket: 'truffly-6368a.firebasestorage.app',
    androidClientId: '227895447148-7h9qte1hikce0n6f3gh6m3e39g2vk11r.apps.googleusercontent.com',
    iosClientId: '227895447148-3arh6ao6qm7tk1091jdteoigk9ggnc7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.trufflyApp',
  );
}
